/**
 * Design-to-Storybook Core
 * 
 * Core transformation logic for converting Figma designs to Storybook components
 */

// Types
export * from './types/index.js';

// Extractors
export { extractStyle, extractFills, extractStrokes, extractEffects, generateClassName, inferHTMLTag } from './extractors/styleExtractor.js';
export { createFrameNode, createTextNode, isDesignNode, getNodeBounds, getPrimaryFill, getNodeOpacity, countDescendants } from './extractors/nodeExtractor.js';

// Inference
export { inferProps } from './inference/propsInferrer.js';
export { 
  inferComponentProperties, 
  extractVariants, 
  analyzeVariantCombinations, 
  inferSharedProps,
} from './inference/variantInferrer.js';
export {
  createPropertyMappings,
  inferInteractionStates,
  PRESET_MAPPINGS,
  type ComponentPropertyMapping
} from './inference/propertyMapper.js';
export {
  inferTypescriptDefinition,
  generateRelatedTypes,
  mergeProps,
  generateTypeFile,
  generateReactImports,
  type TypeInferenceConfig,
  type TypeDefinition
} from './inference/typescriptInferrer.js';

// Converters
export { convertStyles, extractDesignTokens, stylesToCSS } from './converters/styleConverter.js';
export { 
  convertToTailwindColor, 
  convertToTailwindRadius, 
  convertToTailwindShadow,
  convertStyleToTailwind,
  generateTailwindConfig,
  type TailwindPreset 
} from './converters/tailwindConverter.js';

// Token Extractor
export { TokenExtractor } from './extractors/tokenExtractor.js';

// Interaction State Exporter
export { InteractionStateExporter } from './extractors/interactionStateExporter.js';

// Generators
export { MDXGenerator, type MDXGeneratorOptions } from './generators/mdxGenerator.js';

// Main Converter
export { DesignConverter, type DesignConverterOptions } from './converter.js';

// Error Handling
export { 
  DesignToStorybookError, 
  Errors, 
  ErrorCode,
  type ConversionError 
} from './utils/errors.js';
export { 
  Logger, 
  createLogger, 
  defaultLogger, 
  silentLogger, 
  verboseLogger,
  LogLevel,
  type LogEntry,
  type LogHandler
} from './utils/logger.js';

// Plugins
export {
  PluginManager,
  officialPlugins,
  type DesignToStorybookPlugin,
  type PluginContext,
  type PluginHook
} from './plugins/pluginSystem.js';
export * from './plugins/pluginExamples.js';

// API
export {
  convertDesign,
  generateDocumentation,
  extractDesignInfo,
  batchConvert
} from './api/converter.js';

/**
 * Main conversion function
 */
import type { DesignNode, ConversionResult, GeneratedComponent } from './types/index.js';
import { inferProps } from './inference/propsInferrer.js';
import { convertStyles } from './converters/styleConverter.js';
import { extractDesignTokens } from './converters/styleConverter.js';

export interface ConvertOptions {
  framework?: 'react' | 'vue' | 'angular';
  styleFormat?: 'css' | 'tailwind';
  includeStories?: boolean;
  includeDocs?: boolean;
  extractTokens?: boolean;
  outputDir?: string;
  componentPrefix?: string;
}

/**
 * Convert Figma nodes to generated components
 */
export function convert(
  nodes: DesignNode[],
  options: Partial<ConvertOptions> = {}
): ConversionResult {
  const opts: Required<ConvertOptions> = {
    framework: options.framework || 'react',
    styleFormat: options.styleFormat || 'css',
    includeStories: options.includeStories ?? true,
    includeDocs: options.includeDocs ?? false,
    extractTokens: options.extractTokens ?? true,
    outputDir: options.outputDir || './components',
    componentPrefix: options.componentPrefix || '',
  };

  const components: GeneratedComponent[] = [];
  const errors: ConversionResult['errors'] = [];

  for (const node of nodes) {
    try {
      const component = convertNode(node, opts);
      components.push(component);
    } catch (error) {
      errors.push({
        nodeId: node.id,
        nodeName: node.name,
        message: error instanceof Error ? error.message : 'Unknown error',
        severity: 'error',
      });
    }
  }

  // Extract design tokens
  const tokens = opts.extractTokens ? extractDesignTokens(nodes) : {
    colors: [],
    spacing: [],
    typography: [],
    borderRadius: [],
    shadows: [],
  };

  return {
    components,
    stories: [], // Stories are generated by the framework-specific generators
    tokens,
    errors,
  };
}

/**
 * Convert a single design node to a generated component
 */
function convertNode(node: DesignNode, options: Required<ConvertOptions>): GeneratedComponent {
  // Infer props from the node
  const props = inferProps(node);

  // Convert styles
  const styles = convertStyles(node, {
    format: options.styleFormat,
    classPrefix: options.componentPrefix,
    extractTokens: options.extractTokens,
  });

  // Generate component name
  const name = toComponentName(node.name);

  return {
    name,
    code: '', // Code is generated by framework-specific generators
    language: options.framework === 'react' ? 'tsx' : options.framework === 'vue' ? 'vue' : 'angular',
    props,
    styles: [styles],
  };
}

/**
 * Convert node name to valid component name
 */
function toComponentName(name: string): string {
  return name
    .split(/[-_\s]+/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('');
}

/**
 * Create a simple component generator for the core package
 * This is used when no framework-specific generator is available
 */
export function createBasicComponentCode(
  component: GeneratedComponent
): string {
  const { name, props, styles } = component;

  // Generate props interface
  const propsInterface = props.length > 0
    ? `\ninterface ${name}Props {\n${props.map(p => `  /** ${p.description || p.name} */\n  ${p.name}${p.required ? '' : '?'}: ${p.type};`).join('\n')}\n}`
    : '';

  // Generate style class
  const styleClass = styles[0]?.className || name.toLowerCase();

  return `${propsInterface}
export const ${name}: React.FC<${name}Props> = ({
${props.map(p => `  ${p.name}${p.required ? '' : '?'},`).join('\n')}
}) => {
  return (
    <div className="${styleClass}">
      {/* Component content */}
    </div>
  );
};
`;
}
